const questionBank = [
  {
    question: "Which city is the capital of Canada?",
    options: ["Toronto", "Montreal", "Vancouver", "Ottawa"],
    correctAnswer: "Ottawa",
    explanation:
      "Ottawa is the capital city of Canada, located in the province of Ontario.",
    imageLink: "https://www.countryflags.io/ca/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest country in Africa by area?",
    options: ["Nigeria", "Sudan", "Algeria", "Egypt"],
    correctAnswer: "Algeria",
    explanation:
      "Algeria is the largest country in Africa by area, covering over 2.38 million square kilometers.",
    imageLink: "https://www.countryflags.io/dz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is home to the world's largest rainforest?",
    options: ["Brazil", "Indonesia", "Congo", "Peru"],
    correctAnswer: "Brazil",
    explanation:
      "Brazil is home to the Amazon Rainforest, the largest rainforest in the world.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which African country has the highest population?",
    options: ["Nigeria", "South Africa", "Egypt", "Ethiopia"],
    correctAnswer: "Nigeria",
    explanation:
      "Nigeria is the most populous country in Africa, with over 200 million people.",
    imageLink: "https://www.countryflags.io/ng/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river flows through the Grand Canyon?",
    options: ["Mississippi", "Colorado", "Amazon", "Missouri"],
    correctAnswer: "Colorado",
    explanation:
      "The Colorado River flows through the Grand Canyon, creating its iconic landscapes over millions of years.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the longest river in Asia?",
    options: ["Yellow River", "Mekong", "Yangtze", "Ganges"],
    correctAnswer: "Yangtze",
    explanation:
      "The Yangtze River in China is the longest river in Asia, stretching over 6,300 kilometers.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest country in South America by area?",
    options: ["Suriname", "Guyana", "Uruguay", "Ecuador"],
    correctAnswer: "Suriname",
    explanation:
      "Suriname is the smallest country in South America by area, covering approximately 165,000 square kilometers.",
    imageLink: "https://www.countryflags.io/sr/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which sea separates Europe and Africa?",
    options: ["Red Sea", "Mediterranean Sea", "Baltic Sea", "Black Sea"],
    correctAnswer: "Mediterranean Sea",
    explanation:
      "The Mediterranean Sea separates Europe and Africa, stretching from the Strait of Gibraltar to the Middle East.",
    imageLink: "https://www.countryflags.io/ma/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest island in the world?",
    options: ["Greenland", "New Guinea", "Borneo", "Madagascar"],
    correctAnswer: "Greenland",
    explanation:
      "Greenland is the largest island in the world, covering more than 2 million square kilometers.",
    imageLink: "https://www.countryflags.io/gl/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the longest river in Africa?",
    options: ["Nile", "Congo", "Zambezi", "Niger"],
    correctAnswer: "Nile",
    explanation:
      "The Nile is the longest river in Africa, flowing through 11 countries over a length of about 6,650 kilometers.",
    imageLink: "https://www.countryflags.io/eg/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most volcanoes in the world?",
    options: ["Japan", "Indonesia", "Iceland", "Philippines"],
    correctAnswer: "Indonesia",
    explanation:
      "Indonesia has the most volcanoes in the world, with more than 130 active volcanoes.",
    imageLink: "https://www.countryflags.io/id/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is home to the Great Wall of China?",
    options: ["Mongolia", "China", "South Korea", "Vietnam"],
    correctAnswer: "China",
    explanation:
      "The Great Wall of China is one of the most famous landmarks in the world, stretching over 13,000 miles.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most lakes in the world?",
    options: ["USA", "Finland", "Russia", "Canada"],
    correctAnswer: "Canada",
    explanation:
      "Canada is home to the most lakes in the world, with about 60% of the world's lakes.",
    imageLink: "https://www.countryflags.io/ca/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which country has the tallest mountain in the world, Mount Everest?",
    options: ["Nepal", "India", "China", "Bhutan"],
    correctAnswer: "Nepal",
    explanation:
      "Mount Everest, the tallest mountain in the world, is located on the border of Nepal and China.",
    imageLink: "https://www.countryflags.io/np/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is the driest in the world?",
    options: ["Chile", "Australia", "Egypt", "Namibia"],
    correctAnswer: "Chile",
    explanation:
      "Chile's Atacama Desert is considered the driest place on Earth, with some areas never recording rainfall.",
    imageLink: "https://www.countryflags.io/cl/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the largest population in the world?",
    options: ["India", "China", "USA", "Indonesia"],
    correctAnswer: "China",
    explanation:
      "China has the largest population in the world, with over 1.4 billion people.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital city of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    correctAnswer: "Canberra",
    explanation:
      "Canberra is the capital city of Australia, chosen as a compromise between Sydney and Melbourne.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest ocean in the world?",
    options: ["Atlantic", "Pacific", "Indian", "Arctic"],
    correctAnswer: "Pacific",
    explanation:
      "The Pacific Ocean is the largest ocean in the world, covering more than 63 million square miles.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the longest river in Europe?",
    options: ["Danube", "Rhine", "Volga", "Dnieper"],
    correctAnswer: "Volga",
    explanation:
      "The Volga River, located in Russia, is the longest river in Europe, measuring about 3,531 kilometers.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },

  {
    question: "Which continent has the most countries?",
    options: ["Asia", "Europe", "Africa", "South America"],
    correctAnswer: "Africa",
    explanation:
      "Africa has the most countries of any continent, with 54 recognized sovereign nations.",
    imageLink: "https://www.countryflags.io/za/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Thailand?",
    options: ["Hanoi", "Bangkok", "Manila", "Yangon"],
    correctAnswer: "Bangkok",
    explanation:
      "Bangkok is the capital and largest city of Thailand, known for its vibrant street life and cultural landmarks.",
    imageLink: "https://www.countryflags.io/th/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the highest capital city in the world?",
    options: ["La Paz", "Quito", "Kathmandu", "Thimphu"],
    correctAnswer: "La Paz",
    explanation:
      "La Paz, Bolivia, is the highest capital city in the world at about 3,650 meters above sea level.",
    imageLink: "https://www.countryflags.io/bo/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most UNESCO World Heritage Sites?",
    options: ["France", "China", "Italy", "Spain"],
    correctAnswer: "Italy",
    explanation:
      "Italy has the most UNESCO World Heritage Sites, with 58 recognized cultural and natural landmarks.",
    imageLink: "https://www.countryflags.io/it/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known as the 'Pearl of the Indian Ocean'?",
    options: ["Maldives", "Sri Lanka", "Mauritius", "Seychelles"],
    correctAnswer: "Sri Lanka",
    explanation:
      "Sri Lanka is often referred to as the 'Pearl of the Indian Ocean' due to its scenic beauty and location.",
    imageLink: "https://www.countryflags.io/lk/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the longest river in Europe?",
    options: ["Danube", "Rhine", "Volga", "Dnieper"],
    correctAnswer: "Volga",
    explanation:
      "The Volga River, located in Russia, is the longest river in Europe, measuring about 3,531 kilometers.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which African country was never colonized?",
    options: ["Liberia", "Ethiopia", "Ghana", "Egypt"],
    correctAnswer: "Ethiopia",
    explanation:
      "Ethiopia was never colonized by European powers, successfully resisting Italian colonization attempts.",
    imageLink: "https://www.countryflags.io/et/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest peninsula in the world?",
    options: [
      "Arabian Peninsula",
      "Yucatan Peninsula",
      "Balkan Peninsula",
      "Iberian Peninsula",
    ],
    correctAnswer: "Arabian Peninsula",
    explanation:
      "The Arabian Peninsula is the largest peninsula in the world, covering an area of about 3.2 million square kilometers.",
    imageLink: "https://www.countryflags.io/sa/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the longest continental mountain range in the world?",
    options: ["Rocky Mountains", "Andes", "Himalayas", "Alps"],
    correctAnswer: "Andes",
    explanation:
      "The Andes is the longest continental mountain range in the world, stretching over 7,000 kilometers along South America's western coast.",
    imageLink: "https://www.countryflags.io/cl/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which continent has the highest average elevation?",
    options: ["Asia", "Antarctica", "South America", "Africa"],
    correctAnswer: "Antarctica",
    explanation:
      "Antarctica has the highest average elevation of any continent due to its thick ice sheets.",
    imageLink: "https://www.countryflags.io/aq/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country in South America is landlocked?",
    options: ["Chile", "Argentina", "Bolivia", "Colombia"],
    correctAnswer: "Bolivia",
    explanation:
      "Bolivia is one of two landlocked countries in South America, the other being Paraguay.",
    imageLink: "https://www.countryflags.io/bo/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest country by area in Africa?",
    options: ["Seychelles", "Comoros", "Mauritius", "São Tomé and Príncipe"],
    correctAnswer: "Seychelles",
    explanation:
      "Seychelles is the smallest country in Africa by area, covering about 459 square kilometers.",
    imageLink: "https://www.countryflags.io/sc/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest island in the Mediterranean Sea?",
    options: ["Crete", "Sicily", "Cyprus", "Sardinia"],
    correctAnswer: "Sicily",
    explanation:
      "Sicily is the largest island in the Mediterranean Sea, located just off the 'toe' of Italy's 'boot.'",
    imageLink: "https://www.countryflags.io/it/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest desert in Asia?",
    options: ["Gobi", "Thar", "Karakum", "Arabian"],
    correctAnswer: "Gobi",
    explanation:
      "The Gobi Desert is the largest desert in Asia, spanning parts of northern China and southern Mongolia.",
    imageLink: "https://www.countryflags.io/mn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the highest waterfall in the world?",
    options: ["USA", "Norway", "Venezuela", "South Africa"],
    correctAnswer: "Venezuela",
    explanation:
      "Angel Falls in Venezuela is the highest waterfall in the world, with a height of 979 meters.",
    imageLink: "https://www.countryflags.io/ve/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest continent by land area?",
    options: ["Europe", "Australia", "Antarctica", "South America"],
    correctAnswer: "Australia",
    explanation:
      "Australia is the smallest continent by land area, though it is often considered both a country and a continent.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most islands?",
    options: ["Sweden", "Philippines", "Indonesia", "Finland"],
    correctAnswer: "Sweden",
    explanation:
      "Sweden has the most islands of any country, with over 221,800 islands.",
    imageLink: "https://www.countryflags.io/se/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most pyramids?",
    options: ["Mexico", "Egypt", "Sudan", "Peru"],
    correctAnswer: "Sudan",
    explanation:
      "Sudan has more pyramids than any other country, with about 200 pyramids located at the sites of ancient Nubian kingdoms.",
    imageLink: "https://www.countryflags.io/sd/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city has the largest population in the world?",
    options: ["Shanghai", "Tokyo", "Mumbai", "Mexico City"],
    correctAnswer: "Tokyo",
    explanation:
      "Tokyo, Japan, has the largest metropolitan population in the world, with over 37 million residents.",
    imageLink: "https://www.countryflags.io/jp/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which continent has the most countries?",
    options: ["Asia", "Africa", "Europe", "South America"],
    correctAnswer: "Africa",
    explanation:
      "Africa has the most countries of any continent, with 54 recognized sovereign nations.",
    imageLink: "https://www.countryflags.io/za/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known as the 'Land of Fire'?",
    options: ["Azerbaijan", "Iceland", "Japan", "Chile"],
    correctAnswer: "Azerbaijan",
    explanation:
      "Azerbaijan is known as the 'Land of Fire' due to its natural gas reserves and historical fire-worshipping culture.",
    imageLink: "https://www.countryflags.io/az/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is the most populous in Africa?",
    options: ["Cairo", "Lagos", "Johannesburg", "Kinshasa"],
    correctAnswer: "Lagos",
    explanation:
      "Lagos, Nigeria, is the most populous city in Africa, with over 21 million people.",
    imageLink: "https://www.countryflags.io/ng/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is the smallest by population?",
    options: ["Tuvalu", "Vatican City", "Monaco", "Nauru"],
    correctAnswer: "Vatican City",
    explanation:
      "Vatican City has the smallest population in the world, with fewer than 1,000 residents.",
    imageLink: "https://www.countryflags.io/va/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is home to the majority of the Himalayas?",
    options: ["Nepal", "India", "China", "Bhutan"],
    correctAnswer: "Nepal",
    explanation:
      "Nepal is home to the majority of the Himalayas, including Mount Everest, the world's tallest peak.",
    imageLink: "https://www.countryflags.io/np/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the longest coastline in the world?",
    options: ["Canada", "Australia", "Russia", "USA"],
    correctAnswer: "Canada",
    explanation:
      "Canada has the longest coastline in the world, stretching over 202,000 kilometers.",
    imageLink: "https://www.countryflags.io/ca/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest island in the Caribbean?",
    options: ["Jamaica", "Cuba", "Hispaniola", "Puerto Rico"],
    correctAnswer: "Cuba",
    explanation:
      "Cuba is the largest island in the Caribbean, both by area and population.",
    imageLink: "https://www.countryflags.io/cu/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is located on two continents?",
    options: ["Moscow", "Istanbul", "Cairo", "Sydney"],
    correctAnswer: "Istanbul",
    explanation:
      "Istanbul, Turkey, is located on both the European and Asian continents.",
    imageLink: "https://www.countryflags.io/tr/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest lake in Africa?",
    options: ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
    correctAnswer: "Lake Victoria",
    explanation: "Lake Victoria is the largest lake in Africa by surface area.",
    imageLink: "https://www.countryflags.io/tz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the highest number of active volcanoes?",
    options: ["Japan", "USA", "Indonesia", "Philippines"],
    correctAnswer: "Indonesia",
    explanation:
      "Indonesia has the highest number of active volcanoes in the world due to its location on the Pacific Ring of Fire.",
    imageLink: "https://www.countryflags.io/id/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is the capital of the United Arab Emirates?",
    options: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain"],
    correctAnswer: "Abu Dhabi",
    explanation:
      "Abu Dhabi is the capital of the UAE, while Dubai is the largest city.",
    imageLink: "https://www.countryflags.io/ae/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which is the second-largest country by land area in South America?",
    options: ["Chile", "Argentina", "Brazil", "Colombia"],
    correctAnswer: "Argentina",
    explanation:
      "Argentina is the second-largest country in South America by land area, after Brazil.",
    imageLink: "https://www.countryflags.io/ar/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the longest river in North America?",
    options: [
      "Mississippi River",
      "Missouri River",
      "Colorado River",
      "Yukon River",
    ],
    correctAnswer: "Missouri River",
    explanation:
      "The Missouri River is the longest river in North America, stretching over 2,341 miles.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the tallest building in the United States?",
    options: [
      "Willis Tower",
      "World Trade Center",
      "Empire State Building",
      "Chrysler Building",
    ],
    correctAnswer: "World Trade Center",
    explanation:
      "One World Trade Center in New York City is the tallest building in the US, standing at 1,776 feet.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known for its fjords?",
    options: ["Sweden", "Norway", "Finland", "Denmark"],
    correctAnswer: "Norway",
    explanation:
      "Norway is famous for its fjords, which are steep-sided valleys formed by glaciers.",
    imageLink: "https://www.countryflags.io/no/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which desert covers most of Mongolia?",
    options: ["Sahara", "Gobi", "Kalahari", "Atacama"],
    correctAnswer: "Gobi",
    explanation: "The Gobi Desert covers much of Mongolia and northern China.",
    imageLink: "https://www.countryflags.io/mn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is the largest exporter of coffee?",
    options: ["Colombia", "Vietnam", "Ethiopia", "Brazil"],
    correctAnswer: "Brazil",
    explanation:
      "Brazil is the largest exporter of coffee in the world, accounting for about a third of global production.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is home to the Great Barrier Reef?",
    options: ["Australia", "Indonesia", "Philippines", "New Zealand"],
    correctAnswer: "Australia",
    explanation:
      "The Great Barrier Reef, the world's largest coral reef system, is located off the coast of Queensland, Australia.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the largest Muslim population?",
    options: ["Pakistan", "Saudi Arabia", "India", "Indonesia"],
    correctAnswer: "Indonesia",
    explanation:
      "Indonesia has the largest Muslim population in the world, with over 220 million Muslims.",
    imageLink: "https://www.countryflags.io/id/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river flows through London?",
    options: ["Thames", "Seine", "Rhine", "Danube"],
    correctAnswer: "Thames",
    explanation:
      "The Thames River flows through London, providing a key route for trade and transport.",
    imageLink: "https://www.countryflags.io/gb/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is the capital of the Philippines?",
    options: ["Cebu", "Davao", "Quezon City", "Manila"],
    correctAnswer: "Manila",
    explanation:
      "Manila is the capital of the Philippines and one of the most densely populated cities in the world.",
    imageLink: "https://www.countryflags.io/ph/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is known as the 'Gateway to the West' in the USA?",
    options: ["New York", "Chicago", "Los Angeles", "St. Louis"],
    correctAnswer: "St. Louis",
    explanation:
      "St. Louis is known as the 'Gateway to the West' due to its historical role in westward expansion.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the highest mountain in Africa?",
    options: ["Mount Elgon", "Mount Kilimanjaro", "Mount Kenya", "Ras Dashen"],
    correctAnswer: "Mount Kilimanjaro",
    explanation:
      "Mount Kilimanjaro in Tanzania is the highest mountain in Africa, standing at 5,895 meters.",
    imageLink: "https://www.countryflags.io/tz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest island in the Mediterranean Sea?",
    options: ["Crete", "Sicily", "Cyprus", "Sardinia"],
    correctAnswer: "Sicily",
    explanation:
      "Sicily is the largest island in the Mediterranean Sea, located just off the 'toe' of Italy's 'boot.'",
    imageLink: "https://www.countryflags.io/it/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is the largest in South America by area?",
    options: ["Argentina", "Brazil", "Chile", "Peru"],
    correctAnswer: "Brazil",
    explanation:
      "Brazil is the largest country in South America, covering almost half the continent's landmass.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which country is home to the oldest continuously inhabited city in the world?",
    options: ["Egypt", "Greece", "Iraq", "Syria"],
    correctAnswer: "Syria",
    explanation:
      "Damascus, the capital of Syria, is considered the oldest continuously inhabited city in the world.",
    imageLink: "https://www.countryflags.io/sy/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the largest freshwater lake in the world by volume?",
    options: ["Lake Superior", "Lake Baikal", "Lake Tanganyika", "Caspian Sea"],
    correctAnswer: "Lake Baikal",
    explanation:
      "Lake Baikal in Russia is the largest freshwater lake by volume, holding 20% of the world's fresh surface water.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Iceland?",
    options: ["Helsinki", "Oslo", "Reykjavik", "Copenhagen"],
    correctAnswer: "Reykjavik",
    explanation:
      "Reykjavik is the capital and largest city of Iceland, known for its geothermal activity and stunning landscapes.",
    imageLink: "https://www.countryflags.io/is/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which desert is known for being the driest place on Earth?",
    options: ["Atacama", "Sahara", "Kalahari", "Gobi"],
    correctAnswer: "Atacama",
    explanation:
      "The Atacama Desert in Chile is known as the driest place on Earth, with some areas having never recorded rainfall.",
    imageLink: "https://www.countryflags.io/cl/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river is considered the cradle of Chinese civilization?",
    options: ["Yangtze", "Yellow River", "Pearl River", "Liao River"],
    correctAnswer: "Yellow River",
    explanation:
      "The Yellow River, also known as the Huang He, is considered the cradle of Chinese civilization.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Switzerland?",
    options: ["Zurich", "Geneva", "Bern", "Lucerne"],
    correctAnswer: "Bern",
    explanation:
      "Bern is the capital city of Switzerland, despite Zurich being the country's largest city.",
    imageLink: "https://www.countryflags.io/ch/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which mountain range is home to Mount Everest?",
    options: ["Rockies", "Andes", "Alps", "Himalayas"],
    correctAnswer: "Himalayas",
    explanation:
      "Mount Everest, the tallest mountain in the world, is part of the Himalayas mountain range.",
    imageLink: "https://www.countryflags.io/np/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which river forms part of the border between France and Germany?",
    options: ["Seine", "Rhine", "Danube", "Elbe"],
    correctAnswer: "Rhine",
    explanation:
      "The Rhine River forms part of the border between France and Germany.",
    imageLink: "https://www.countryflags.io/de/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is Mount Fuji located in?",
    options: ["South Korea", "China", "Japan", "Philippines"],
    correctAnswer: "Japan",
    explanation:
      "Mount Fuji, a stratovolcano, is located in Japan and is a cultural icon of the country.",
    imageLink: "https://www.countryflags.io/jp/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country shares the longest land border with India?",
    options: ["China", "Bangladesh", "Pakistan", "Nepal"],
    correctAnswer: "Bangladesh",
    explanation:
      "Bangladesh shares the longest land border with India, stretching over 4,000 kilometers.",
    imageLink: "https://www.countryflags.io/in/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which country has the largest number of UNESCO World Heritage Sites?",
    options: ["Italy", "China", "France", "Spain"],
    correctAnswer: "Italy",
    explanation:
      "Italy has the largest number of UNESCO World Heritage Sites, known for its rich cultural history.",
    imageLink: "https://www.countryflags.io/it/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Kenya?",
    options: ["Nairobi", "Mombasa", "Kampala", "Dodoma"],
    correctAnswer: "Nairobi",
    explanation:
      "Nairobi is the capital and largest city of Kenya, known as a hub for East African trade.",
    imageLink: "https://www.countryflags.io/ke/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which European country has the most islands?",
    options: ["Greece", "Norway", "Sweden", "Finland"],
    correctAnswer: "Sweden",
    explanation:
      "Sweden has the most islands of any European country, with over 200,000 islands.",
    imageLink: "https://www.countryflags.io/se/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is the largest by population in Canada?",
    options: ["Vancouver", "Montreal", "Ottawa", "Toronto"],
    correctAnswer: "Toronto",
    explanation:
      "Toronto is the largest city by population in Canada, known for its diverse culture and skyline.",
    imageLink: "https://www.countryflags.io/ca/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which continent is home to the Amazon Rainforest?",
    options: ["Africa", "Asia", "South America", "Australia"],
    correctAnswer: "South America",
    explanation:
      "The Amazon Rainforest, the largest tropical rainforest in the world, is located in South America.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the official language of Brazil?",
    options: ["Spanish", "Portuguese", "French", "English"],
    correctAnswer: "Portuguese",
    explanation:
      "Portuguese is the official language of Brazil, a legacy of the country's colonial history.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river is the longest in Australia?",
    options: [
      "Murray River",
      "Darling River",
      "Murrumbidgee River",
      "Swan River",
    ],
    correctAnswer: "Murray River",
    explanation:
      "The Murray River is the longest river in Australia, flowing over 2,500 kilometers.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which mountain range forms the natural border between France and Spain?",
    options: ["Alps", "Pyrenees", "Carpathians", "Apennines"],
    correctAnswer: "Pyrenees",
    explanation:
      "The Pyrenees mountain range forms the natural border between France and Spain.",
    imageLink: "https://www.countryflags.io/fr/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which country is home to the world's tallest building, the Burj Khalifa?",
    options: ["USA", "China", "Saudi Arabia", "UAE"],
    correctAnswer: "UAE",
    explanation:
      "The Burj Khalifa in Dubai, UAE, is the world's tallest building, standing at 828 meters.",
    imageLink: "https://www.countryflags.io/ae/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which desert covers much of northern Africa?",
    options: ["Gobi", "Sahara", "Kalahari", "Sonoran"],
    correctAnswer: "Sahara",
    explanation:
      "The Sahara Desert is the largest hot desert in the world, covering much of northern Africa.",
    imageLink: "https://www.countryflags.io/ma/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country controls the Suez Canal?",
    options: ["Israel", "Egypt", "Saudi Arabia", "Jordan"],
    correctAnswer: "Egypt",
    explanation:
      "The Suez Canal is controlled by Egypt and connects the Mediterranean Sea to the Red Sea.",
    imageLink: "https://www.countryflags.io/eg/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the longest river in Europe?",
    options: ["Danube", "Volga", "Rhine", "Dnieper"],
    correctAnswer: "Volga",
    explanation:
      "The Volga River, which flows through Russia, is the longest river in Europe, stretching over 3,500 kilometers.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which island nation lies directly east of Madagascar?",
    options: ["Seychelles", "Mauritius", "Comoros", "Sri Lanka"],
    correctAnswer: "Mauritius",
    explanation:
      "Mauritius is an island nation that lies directly east of Madagascar in the Indian Ocean.",
    imageLink: "https://www.countryflags.io/mu/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest ocean in the world?",
    options: ["Atlantic", "Pacific", "Arctic", "Indian"],
    correctAnswer: "Arctic",
    explanation:
      "The Arctic Ocean is the smallest ocean, covering around 5.4 million square miles.",
    imageLink: "https://www.countryflags.io/no/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the largest population in Africa?",
    options: ["Ethiopia", "Egypt", "South Africa", "Nigeria"],
    correctAnswer: "Nigeria",
    explanation:
      "Nigeria is the most populous country in Africa, with over 200 million people.",
    imageLink: "https://www.countryflags.io/ng/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which island is both a country and a continent?",
    options: ["Greenland", "Madagascar", "Australia", "New Zealand"],
    correctAnswer: "Australia",
    explanation:
      "Australia is unique as both a country and a continent, and is the smallest of the seven continents.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which European capital city is known for its canals and is often called 'Venice of the North'?",
    options: ["Amsterdam", "Stockholm", "Copenhagen", "Brussels"],
    correctAnswer: "Amsterdam",
    explanation:
      "Amsterdam, the capital of the Netherlands, is known for its canals and is often referred to as the 'Venice of the North.'",
    imageLink: "https://www.countryflags.io/nl/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known as the 'Land of the Midnight Sun'?",
    options: ["Sweden", "Norway", "Iceland", "Finland"],
    correctAnswer: "Norway",
    explanation:
      "Norway is known as the 'Land of the Midnight Sun' because the sun remains visible at midnight in its northern regions during the summer months.",
    imageLink: "https://www.countryflags.io/no/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which body of water separates Saudi Arabia from Africa?",
    options: ["Persian Gulf", "Red Sea", "Mediterranean Sea", "Arabian Sea"],
    correctAnswer: "Red Sea",
    explanation:
      "The Red Sea separates Saudi Arabia from Africa, forming part of a major shipping route.",
    imageLink: "https://www.countryflags.io/sa/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of New Zealand?",
    options: ["Wellington", "Auckland", "Christchurch", "Dunedin"],
    correctAnswer: "Wellington",
    explanation:
      "Wellington is the capital of New Zealand, located at the southern tip of the North Island.",
    imageLink: "https://www.countryflags.io/nz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which strait separates the islands of New Zealand?",
    options: ["Cook Strait", "Bass Strait", "Bering Strait", "Taiwan Strait"],
    correctAnswer: "Cook Strait",
    explanation:
      "The Cook Strait separates New Zealand's North and South Islands.",
    imageLink: "https://www.countryflags.io/nz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which US state is known as 'The Last Frontier'?",
    options: ["Hawaii", "California", "Alaska", "Montana"],
    correctAnswer: "Alaska",
    explanation:
      "Alaska is known as 'The Last Frontier' due to its remote location and vast, unexplored wilderness.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known as the 'Land of a Thousand Lakes'?",
    options: ["Sweden", "Norway", "Finland", "Canada"],
    correctAnswer: "Finland",
    explanation:
      "Finland is known as the 'Land of a Thousand Lakes,' with around 188,000 lakes.",
    imageLink: "https://www.countryflags.io/fi/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which city is known as the 'Big Apple'?",
    options: ["Los Angeles", "Chicago", "New York", "San Francisco"],
    correctAnswer: "New York",
    explanation:
      "New York City is commonly known as the 'Big Apple,' a nickname popularized in the 1920s.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which mountain is known as the 'Roof of Africa'?",
    options: ["Kilimanjaro", "Mount Kenya", "Ras Dashen", "Mount Elgon"],
    correctAnswer: "Kilimanjaro",
    explanation:
      "Mount Kilimanjaro in Tanzania is known as the 'Roof of Africa' due to its height of 5,895 meters.",
    imageLink: "https://www.countryflags.io/tz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which river forms part of the border between the USA and Mexico?",
    options: ["Mississippi", "Colorado", "Rio Grande", "Columbia"],
    correctAnswer: "Rio Grande",
    explanation:
      "The Rio Grande forms part of the border between the USA and Mexico, flowing from Colorado to the Gulf of Mexico.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which African lake is the world's second-largest freshwater lake by area?",
    options: [
      "Lake Victoria",
      "Lake Tanganyika",
      "Lake Malawi",
      "Lake Turkana",
    ],
    correctAnswer: "Lake Victoria",
    explanation:
      "Lake Victoria is Africa’s largest lake and the world’s second-largest freshwater lake by area, after Lake Superior.",
    imageLink: "https://www.countryflags.io/ug/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river runs through Baghdad?",
    options: ["Euphrates", "Tigris", "Nile", "Jordan"],
    correctAnswer: "Tigris",
    explanation:
      "The Tigris River runs through Baghdad, one of the two main rivers that define Mesopotamia.",
    imageLink: "https://www.countryflags.io/iq/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known for the historical site of Machu Picchu?",
    options: ["Mexico", "Brazil", "Peru", "Chile"],
    correctAnswer: "Peru",
    explanation:
      "Machu Picchu, an ancient Inca city, is located in Peru and is one of the New Seven Wonders of the World.",
    imageLink: "https://www.countryflags.io/pe/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which US state is known as the 'Sunshine State'?",
    options: ["California", "Texas", "Florida", "Arizona"],
    correctAnswer: "Florida",
    explanation:
      "Florida is known as the 'Sunshine State' due to its warm climate and many sunny days throughout the year.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the most populous city in Brazil?",
    options: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    correctAnswer: "Sao Paulo",
    explanation:
      "São Paulo is Brazil's most populous city, known for its economic and cultural significance.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which ocean lies to the east of Africa?",
    options: ["Atlantic", "Indian", "Pacific", "Southern"],
    correctAnswer: "Indian",
    explanation:
      "The Indian Ocean lies to the east of Africa, providing a major trade route for African and Asian countries.",
    imageLink: "https://www.countryflags.io/in/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river is the longest in South America?",
    options: ["Paraná", "Amazon", "Orinoco", "Magdalena"],
    correctAnswer: "Amazon",
    explanation:
      "The Amazon River, flowing through multiple South American countries, is the longest in South America and has the largest water discharge in the world.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is home to the Great Wall?",
    options: ["Japan", "India", "China", "Mongolia"],
    correctAnswer: "China",
    explanation:
      "The Great Wall of China is a historical series of fortifications built to protect Chinese states from invasions.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Argentina?",
    options: ["Buenos Aires", "Lima", "Caracas", "Santiago"],
    correctAnswer: "Buenos Aires",
    explanation:
      "Buenos Aires is the capital and largest city of Argentina, known for its rich European-style architecture.",
    imageLink: "https://www.countryflags.io/ar/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest country in the world by land area?",
    options: ["Canada", "China", "USA", "Russia"],
    correctAnswer: "Russia",
    explanation:
      "Russia is the largest country by land area, covering over 17 million square kilometers.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river is the longest in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctAnswer: "Nile",
    explanation:
      "The Nile is the longest river in the world, stretching approximately 6,650 kilometers.",
    imageLink: "https://www.countryflags.io/eg/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest country in the world?",
    options: ["Monaco", "San Marino", "Liechtenstein", "Vatican City"],
    correctAnswer: "Vatican City",
    explanation:
      "Vatican City is the smallest country, both by population and area, located within Rome, Italy.",
    imageLink: "https://www.countryflags.io/va/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which ocean is the largest in the world?",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    correctAnswer: "Pacific",
    explanation:
      "The Pacific Ocean is the largest, covering more than 63 million square miles of surface area.",
    imageLink: "https://www.countryflags.io/jp/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Australia?",
    options: ["Sydney", "Canberra", "Melbourne", "Brisbane"],
    correctAnswer: "Canberra",
    explanation:
      "Canberra is the capital of Australia, chosen to be a compromise between Sydney and Melbourne.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most time zones?",
    options: ["USA", "Russia", "France", "China"],
    correctAnswer: "France",
    explanation:
      "France has the most time zones due to its overseas territories, spanning 12 different time zones.",
    imageLink: "https://www.countryflags.io/fr/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the second-largest continent by land area?",
    options: ["Africa", "Asia", "North America", "Europe"],
    correctAnswer: "Africa",
    explanation:
      "Africa is the second-largest continent by land area, covering 30.37 million square kilometers.",
    imageLink: "https://www.countryflags.io/za/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the southernmost city in the world?",
    options: ["Ushuaia", "Christchurch", "Punta Arenas", "Cape Town"],
    correctAnswer: "Ushuaia",
    explanation:
      "Ushuaia in Argentina is the southernmost city in the world, located in the Tierra del Fuego archipelago.",
    imageLink: "https://www.countryflags.io/ar/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the longest land border in the world?",
    options: ["Russia", "China", "Canada", "Brazil"],
    correctAnswer: "Russia",
    explanation:
      "Russia has the longest land border in the world, stretching over 22,000 kilometers.",
    imageLink: "https://www.countryflags.io/ru/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the highest mountain in the Western Hemisphere?",
    options: ["Mount McKinley", "Aconcagua", "Chimborazo", "Mount Logan"],
    correctAnswer: "Aconcagua",
    explanation:
      "Aconcagua in Argentina is the highest mountain in the Western Hemisphere, standing at 6,959 meters.",
    imageLink: "https://www.countryflags.io/ar/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which desert is the largest in North America?",
    options: ["Great Basin", "Mojave", "Sonoran", "Chihuahuan"],
    correctAnswer: "Chihuahuan",
    explanation:
      "The Chihuahuan Desert is the largest desert in North America, spanning parts of Mexico and the US.",
    imageLink: "https://www.countryflags.io/mx/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Kazakhstan?",
    options: ["Almaty", "Astana", "Bishkek", "Tashkent"],
    correctAnswer: "Astana",
    explanation:
      "Astana, renamed Nur-Sultan between 2019 and 2022, is the capital of Kazakhstan.",
    imageLink: "https://www.countryflags.io/kz/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the longest coastline in Africa?",
    options: ["South Africa", "Somalia", "Libya", "Egypt"],
    correctAnswer: "Somalia",
    explanation:
      "Somalia has the longest coastline in Africa, stretching for about 3,333 kilometers.",
    imageLink: "https://www.countryflags.io/so/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which European country has the most castles?",
    options: ["Germany", "France", "Spain", "Italy"],
    correctAnswer: "Germany",
    explanation:
      "Germany has the most castles in Europe, with over 25,000 castles scattered across the country.",
    imageLink: "https://www.countryflags.io/de/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the largest Buddhist population?",
    options: ["Thailand", "India", "China", "Japan"],
    correctAnswer: "China",
    explanation:
      "China has the largest Buddhist population in the world, with more than 250 million Buddhists.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which river runs through Paris?",
    options: ["Danube", "Seine", "Thames", "Rhine"],
    correctAnswer: "Seine",
    explanation:
      "The Seine River runs through Paris, winding its way through the French capital.",
    imageLink: "https://www.countryflags.io/fr/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the capital of Malta?",
    options: ["Valletta", "Sliema", "Mdina", "Gozo"],
    correctAnswer: "Valletta",
    explanation:
      "Valletta is the capital city of Malta, known for its historical sites dating back to the 16th century.",
    imageLink: "https://www.countryflags.io/mt/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country does the Danube River not flow through?",
    options: ["Austria", "Germany", "Poland", "Romania"],
    correctAnswer: "Poland",
    explanation:
      "The Danube flows through 10 countries in Europe, but Poland is not one of them.",
    imageLink: "https://www.countryflags.io/at/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which is the deepest lake in North America?",
    options: ["Crater Lake", "Lake Tahoe", "Great Slave Lake", "Lake Superior"],
    correctAnswer: "Great Slave Lake",
    explanation:
      "Great Slave Lake in Canada is the deepest lake in North America, reaching depths of over 600 meters.",
    imageLink: "https://www.countryflags.io/ca/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country has the most official languages?",
    options: ["India", "Switzerland", "South Africa", "Zimbabwe"],
    correctAnswer: "Zimbabwe",
    explanation:
      "Zimbabwe has 16 official languages, making it the country with the most official languages in the world.",
    imageLink: "https://www.countryflags.io/zw/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button",
  },
  {
    question: "What is the largest desert in Europe?",
    options: ["Tabernas", "Bardenas Reales", "Monegros", "Thar"],
    correctAnswer: "Tabernas",
    explanation:
      "The Tabernas Desert in Spain is Europe's largest desert, located in the Andalusian region.",
    imageLink: "https://www.countryflags.io/es/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country shares borders with 14 nations?",
    options: ["Russia", "China", "Brazil", "India"],
    correctAnswer: "China",
    explanation:
      "China shares borders with 14 countries, including Russia, India, and Mongolia.",
    imageLink: "https://www.countryflags.io/cn/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which island is the smallest country by area in the world?",
    options: ["Vatican City", "Nauru", "Monaco", "Tuvalu"],
    correctAnswer: "Vatican City",
    explanation:
      "Vatican City is the smallest country by area, covering just 44 hectares (110 acres).",
    imageLink: "https://www.countryflags.io/va/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is known as the 'Land of the Rising Sun'?",
    options: ["Japan", "South Korea", "China", "Thailand"],
    correctAnswer: "Japan",
    explanation:
      "Japan is often referred to as the 'Land of the Rising Sun' due to its geographic location to the east of the Asian continent.",
    imageLink: "https://www.countryflags.io/jp/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which African country has three capital cities?",
    options: ["South Africa", "Nigeria", "Ethiopia", "Sudan"],
    correctAnswer: "South Africa",
    explanation:
      "South Africa is unique in having three capital cities: Pretoria, Cape Town, and Bloemfontein.",
    imageLink: "https://www.countryflags.io/za/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which European city is built on 14 islands?",
    options: ["Venice", "Stockholm", "Amsterdam", "Helsinki"],
    correctAnswer: "Stockholm",
    explanation:
      "Stockholm, Sweden's capital, is built on 14 islands connected by 57 bridges.",
    imageLink: "https://www.countryflags.io/se/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the southernmost point in mainland Asia?",
    options: ["Singapore", "Johor Bahru", "Tanjung Piai", "Batam"],
    correctAnswer: "Tanjung Piai",
    explanation:
      "Tanjung Piai, located in Malaysia, is the southernmost point of mainland Asia.",
    imageLink: "https://www.countryflags.io/my/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which river forms the border between the United States and Mexico?",
    options: [
      "Colorado River",
      "Rio Grande",
      "Mississippi River",
      "Columbia River",
    ],
    correctAnswer: "Rio Grande",
    explanation:
      "The Rio Grande forms much of the border between the United States and Mexico.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest U.S. state by area?",
    options: ["Delaware", "Connecticut", "Rhode Island", "New Jersey"],
    correctAnswer: "Rhode Island",
    explanation:
      "Rhode Island is the smallest U.S. state by area, covering about 1,034 square miles.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the largest island in the Caribbean?",
    options: ["Jamaica", "Puerto Rico", "Cuba", "Hispaniola"],
    correctAnswer: "Cuba",
    explanation:
      "Cuba is the largest island in the Caribbean by both area and population.",
    imageLink: "https://www.countryflags.io/cu/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which desert is the largest in Australia?",
    options: [
      "Great Victoria Desert",
      "Simpson Desert",
      "Tanami Desert",
      "Great Sandy Desert",
    ],
    correctAnswer: "Great Victoria Desert",
    explanation:
      "The Great Victoria Desert is the largest desert in Australia, covering over 348,000 square kilometers.",
    imageLink: "https://www.countryflags.io/au/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which U.S. state has the longest coastline?",
    options: ["California", "Florida", "Alaska", "Hawaii"],
    correctAnswer: "Alaska",
    explanation:
      "Alaska has the longest coastline of any U.S. state, with over 6,640 miles of coastline.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which island in the Pacific Ocean is the largest by area?",
    options: ["New Guinea", "Hawaii", "Fiji", "New Caledonia"],
    correctAnswer: "New Guinea",
    explanation:
      "New Guinea is the largest island in the Pacific Ocean, shared by Papua New Guinea and Indonesia.",
    imageLink: "https://www.countryflags.io/pg/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "Which country is famous for having 50% of the world's geysers?",
    options: ["Russia", "Iceland", "United States", "New Zealand"],
    correctAnswer: "United States",
    explanation:
      "The United States, particularly Yellowstone National Park, is home to more than 50% of the world's geysers.",
    imageLink: "https://www.countryflags.io/us/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question:
      "Which continent is known for having the largest tropical rainforest?",
    options: ["Africa", "South America", "Asia", "Australia"],
    correctAnswer: "South America",
    explanation:
      "South America is home to the Amazon Rainforest, the largest tropical rainforest in the world.",
    imageLink: "https://www.countryflags.io/br/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
  {
    question: "What is the smallest country by population?",
    options: ["Tuvalu", "San Marino", "Nauru", "Vatican City"],
    correctAnswer: "Vatican City",
    explanation:
      "Vatican City is the smallest country by population, with fewer than 1,000 residents.",
    imageLink: "https://www.countryflags.io/va/flat/64.png",
    questionAudio: "https://www.soundjay.com/button/beep-07.wav",
    optionsAudio: "https://www.soundjay.com/button/beep-07.wav",
    answerAudio: "https://www.soundjay.com/button/beep-07.wav",
    explanationAudio: "https://www.soundjay.com/button/beep-07.wav",
  },
];

module.exports = questionBank;
